# fly.toml app configuration file generated for heb-object-detection on 2023-12-07T22:42:05-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "heb-object-detection"
primary_region = "dfw"
kill_signal = "SIGTERM"

[build]

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "heb-object-detection.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
